<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HFJIJJP" failures="0" tests="4" name="com.testng.Testng_Timeout" time="3.053" errors="1" timestamp="2022-08-30T12:35:51 IST" skipped="0">
  <testcase classname="com.testng.Testng_Timeout" name="cMethod" time="1.011"/>
  <testcase classname="com.testng.Testng_Timeout" name="bMethod" time="1.011"/>
  <testcase classname="com.testng.Testng_Timeout" name="dMethod" time="0.002"/>
  <testcase classname="com.testng.Testng_Timeout" name="aMethod" time="1.029">
    <error message="Method com.testng.Testng_Timeout.aMethod() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.Testng_Timeout.aMethod() didn't finish within the time-out 1000
at java.base@11.0.16/java.util.concurrent.FutureTask.setException(FutureTask.java:247)
at java.base@11.0.16/java.util.concurrent.FutureTask.run(FutureTask.java:269)
at java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11.0.16/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- aMethod -->
</testsuite> <!-- com.testng.Testng_Timeout -->
